
DECALmachine: Installing PIL 8.3.1

Platform: Darwin
Python Binary: /Applications/Blender.app/Contents/Resources/3.0/python/bin/python3.9 True
Python Library: /Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9 True
Ensurepip: /Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9/ensurepip True

Modules: /Applications/Blender.app/Contents/Resources/3.0/scripts/modules True
Modules: /Users/giuseppe/Library/Application Support/Blender/3.0/scripts/modules False
Site-Packages: /Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9/site-packages True
User Site-Packages: /Users/giuseppe/.local/lib/python3.9/site-packages False
EasyInstall Path: /Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9/site-packages/easy_install.py False
EasyInstall User Path: /Users/giuseppe/.local/lib/python3.9/site-packages/easy_install.py False



Looking in links: /var/folders/d5/4tnwbfgn3n7gxb8c5xg88gdr0000gn/T/tmpu69vbyfe
Requirement already satisfied: setuptools in /Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9/site-packages (57.4.0)
Requirement already satisfied: pip in /Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9/site-packages (21.2.3)
ERROR: Could not install packages due to an OSError: [Errno 13] Permission denied: '/Users/giuseppe/.local/lib'
Check the permissions.
Traceback (most recent call last):
File "/Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9/runpy.py", line 197, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9/runpy.py", line 87, in _run_code
exec(code, run_globals)
File "/Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9/ensurepip/__main__.py", line 5, in <module>
sys.exit(ensurepip._main())
File "/Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9/ensurepip/__init__.py", line 210, in _main
return _bootstrap(
File "/Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9/ensurepip/__init__.py", line 129, in _bootstrap
return _run_pip(args + [p[0] for p in _PROJECTS], additional_paths)
File "/Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9/ensurepip/__init__.py", line 38, in _run_pip
return subprocess.run([sys.executable, "-c", code], check=True).returncode
File "/Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9/subprocess.py", line 528, in run
raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Applications/Blender.app/Contents/Resources/3.0/python/bin/python3.9', '-c', '\nimport runpy\nimport sys\nsys.path = [\'/var/folders/d5/4tnwbfgn3n7gxb8c5xg88gdr0000gn/T/tmpu69vbyfe/setuptools-57.4.0-py3-none-any.whl\', \'/var/folders/d5/4tnwbfgn3n7gxb8c5xg88gdr0000gn/T/tmpu69vbyfe/pip-21.2.3-py3-none-any.whl\'] + sys.path\nsys.argv[1:] = [\'install\', \'--no-cache-dir\', \'--no-index\', \'--find-links\', \'/var/folders/d5/4tnwbfgn3n7gxb8c5xg88gdr0000gn/T/tmpu69vbyfe\', \'--upgrade\', \'--user\', \'setuptools\', \'pip\']\nrunpy.run_module("pip", run_name="__main__", alter_sys=True)\n']' returned non-zero exit status 1.

ENVIRONMENT
USER: giuseppe
__CFBundleIdentifier: org.blenderfoundation.blender
COMMAND_MODE: unix2003
LOGNAME: giuseppe
PATH: /usr/bin:/bin:/usr/sbin:/sbin
SSH_AUTH_SOCK: /private/tmp/com.apple.launchd.zRQJhXc25r/Listeners
SHELL: /bin/zsh
HOME: /Users/giuseppe
__CF_USER_TEXT_ENCODING: 0x1F5:0:15
TMPDIR: /var/folders/d5/4tnwbfgn3n7gxb8c5xg88gdr0000gn/T/
XPC_SERVICE_NAME: application.org.blenderfoundation.blender.4888352.4888358
XPC_FLAGS: 0x0

DECALmachine: Installing PIL 8.3.1

Platform: Darwin
Python Binary: /Applications/Blender.app/Contents/Resources/3.0/python/bin/python3.9 True
Python Library: /Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9 True
Ensurepip: /Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9/ensurepip True

Modules: /Applications/Blender.app/Contents/Resources/3.0/scripts/modules True
Modules: /Users/giuseppe/Library/Application Support/Blender/3.0/scripts/modules False
Site-Packages: /Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9/site-packages True
User Site-Packages: /Users/giuseppe/.local/lib/python3.9/site-packages False
EasyInstall Path: /Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9/site-packages/easy_install.py False
EasyInstall User Path: /Users/giuseppe/.local/lib/python3.9/site-packages/easy_install.py False



Looking in links: /var/folders/d5/4tnwbfgn3n7gxb8c5xg88gdr0000gn/T/tmpkb3mf37o
Requirement already satisfied: setuptools in /Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9/site-packages (57.4.0)
Requirement already satisfied: pip in /Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9/site-packages (21.2.3)
ERROR: Could not install packages due to an OSError: [Errno 13] Permission denied: '/Users/giuseppe/.local/lib'
Check the permissions.
Traceback (most recent call last):
File "/Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9/runpy.py", line 197, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9/runpy.py", line 87, in _run_code
exec(code, run_globals)
File "/Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9/ensurepip/__main__.py", line 5, in <module>
sys.exit(ensurepip._main())
File "/Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9/ensurepip/__init__.py", line 210, in _main
return _bootstrap(
File "/Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9/ensurepip/__init__.py", line 129, in _bootstrap
return _run_pip(args + [p[0] for p in _PROJECTS], additional_paths)
File "/Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9/ensurepip/__init__.py", line 38, in _run_pip
return subprocess.run([sys.executable, "-c", code], check=True).returncode
File "/Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9/subprocess.py", line 528, in run
raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Applications/Blender.app/Contents/Resources/3.0/python/bin/python3.9', '-c', '\nimport runpy\nimport sys\nsys.path = [\'/var/folders/d5/4tnwbfgn3n7gxb8c5xg88gdr0000gn/T/tmpkb3mf37o/setuptools-57.4.0-py3-none-any.whl\', \'/var/folders/d5/4tnwbfgn3n7gxb8c5xg88gdr0000gn/T/tmpkb3mf37o/pip-21.2.3-py3-none-any.whl\'] + sys.path\nsys.argv[1:] = [\'install\', \'--no-cache-dir\', \'--no-index\', \'--find-links\', \'/var/folders/d5/4tnwbfgn3n7gxb8c5xg88gdr0000gn/T/tmpkb3mf37o\', \'--upgrade\', \'--user\', \'setuptools\', \'pip\']\nrunpy.run_module("pip", run_name="__main__", alter_sys=True)\n']' returned non-zero exit status 1.

ENVIRONMENT
USER: giuseppe
__CFBundleIdentifier: org.blenderfoundation.blender
COMMAND_MODE: unix2003
LOGNAME: giuseppe
PATH: /usr/bin:/bin:/usr/sbin:/sbin
SSH_AUTH_SOCK: /private/tmp/com.apple.launchd.zRQJhXc25r/Listeners
SHELL: /bin/zsh
HOME: /Users/giuseppe
__CF_USER_TEXT_ENCODING: 0x1F5:0:15
TMPDIR: /var/folders/d5/4tnwbfgn3n7gxb8c5xg88gdr0000gn/T/
XPC_SERVICE_NAME: application.org.blenderfoundation.blender.4888352.4888358
XPC_FLAGS: 0x0

DECALmachine: Installing PIL 8.3.1

Platform: Darwin
Python Binary: /Applications/Blender.app/Contents/Resources/3.0/python/bin/python3.9 True
Python Library: /Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9 True
Ensurepip: /Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9/ensurepip True

Modules: /Applications/Blender.app/Contents/Resources/3.0/scripts/modules True
Modules: /Users/giuseppe/Library/Application Support/Blender/3.0/scripts/modules False
Site-Packages: /Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9/site-packages True
User Site-Packages: /Users/giuseppe/.local/lib/python3.9/site-packages False
EasyInstall Path: /Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9/site-packages/easy_install.py False
EasyInstall User Path: /Users/giuseppe/.local/lib/python3.9/site-packages/easy_install.py False



Looking in links: /var/folders/d5/4tnwbfgn3n7gxb8c5xg88gdr0000gn/T/tmpufcgr3tj
Requirement already satisfied: setuptools in /Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9/site-packages (57.4.0)
Requirement already satisfied: pip in /Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9/site-packages (21.2.3)
ERROR: Could not install packages due to an OSError: [Errno 13] Permission denied: '/Users/giuseppe/.local/lib'
Check the permissions.
Traceback (most recent call last):
File "/Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9/runpy.py", line 197, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9/runpy.py", line 87, in _run_code
exec(code, run_globals)
File "/Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9/ensurepip/__main__.py", line 5, in <module>
sys.exit(ensurepip._main())
File "/Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9/ensurepip/__init__.py", line 210, in _main
return _bootstrap(
File "/Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9/ensurepip/__init__.py", line 129, in _bootstrap
return _run_pip(args + [p[0] for p in _PROJECTS], additional_paths)
File "/Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9/ensurepip/__init__.py", line 38, in _run_pip
return subprocess.run([sys.executable, "-c", code], check=True).returncode
File "/Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9/subprocess.py", line 528, in run
raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Applications/Blender.app/Contents/Resources/3.0/python/bin/python3.9', '-c', '\nimport runpy\nimport sys\nsys.path = [\'/var/folders/d5/4tnwbfgn3n7gxb8c5xg88gdr0000gn/T/tmpufcgr3tj/setuptools-57.4.0-py3-none-any.whl\', \'/var/folders/d5/4tnwbfgn3n7gxb8c5xg88gdr0000gn/T/tmpufcgr3tj/pip-21.2.3-py3-none-any.whl\'] + sys.path\nsys.argv[1:] = [\'install\', \'--no-cache-dir\', \'--no-index\', \'--find-links\', \'/var/folders/d5/4tnwbfgn3n7gxb8c5xg88gdr0000gn/T/tmpufcgr3tj\', \'--upgrade\', \'--user\', \'setuptools\', \'pip\']\nrunpy.run_module("pip", run_name="__main__", alter_sys=True)\n']' returned non-zero exit status 1.

ENVIRONMENT
USER: giuseppe
__CFBundleIdentifier: org.blenderfoundation.blender
COMMAND_MODE: unix2003
LOGNAME: giuseppe
PATH: /usr/bin:/bin:/usr/sbin:/sbin
SSH_AUTH_SOCK: /private/tmp/com.apple.launchd.zRQJhXc25r/Listeners
SHELL: /bin/zsh
HOME: /Users/giuseppe
__CF_USER_TEXT_ENCODING: 0x1F5:0:15
TMPDIR: /var/folders/d5/4tnwbfgn3n7gxb8c5xg88gdr0000gn/T/
XPC_SERVICE_NAME: application.org.blenderfoundation.blender.4888352.4888358
XPC_FLAGS: 0x0

DECALmachine: Installing PIL 8.3.1 (Admin)

Platform: Darwin
Python Binary: /Applications/Blender.app/Contents/Resources/3.0/python/bin/python3.9 True
Python Library: /Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9 True
Ensurepip: /Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9/ensurepip True

Modules: /Applications/Blender.app/Contents/Resources/3.0/scripts/modules True
Modules: /Users/giuseppe/Library/Application Support/Blender/3.0/scripts/modules False
Site-Packages: /Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9/site-packages True
User Site-Packages: /Users/giuseppe/.local/lib/python3.9/site-packages False
EasyInstall Path: /Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9/site-packages/easy_install.py False
EasyInstall User Path: /Users/giuseppe/.local/lib/python3.9/site-packages/easy_install.py False



Looking in links: /var/folders/d5/4tnwbfgn3n7gxb8c5xg88gdr0000gn/T/tmpyirjm9rg
Requirement already satisfied: setuptools in /Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9/site-packages (57.4.0)
Requirement already satisfied: pip in /Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9/site-packages (21.2.3)
Requirement already satisfied: pip in /Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9/site-packages (21.2.3)
Collecting pip
Downloading pip-21.3.1-py3-none-any.whl (1.7 MB)
Installing collected packages: pip
Attempting uninstall: pip
Found existing installation: pip 21.2.3
Uninstalling pip-21.2.3:
Successfully uninstalled pip-21.2.3
Successfully installed pip-21.3.1
Collecting Pillow==8.3.1
Downloading Pillow-8.3.1-cp39-cp39-macosx_11_0_arm64.whl (2.7 MB)
Installing collected packages: Pillow
Successfully installed Pillow-8.3.1
Successfully imported PIL's Image module. PIL is ready to go.

ENVIRONMENT
USER: giuseppe
__CFBundleIdentifier: org.blenderfoundation.blender
COMMAND_MODE: unix2003
LOGNAME: giuseppe
PATH: /usr/bin:/bin:/usr/sbin:/sbin
SSH_AUTH_SOCK: /private/tmp/com.apple.launchd.zRQJhXc25r/Listeners
SHELL: /bin/zsh
HOME: /Users/giuseppe
__CF_USER_TEXT_ENCODING: 0x1F5:0:15
TMPDIR: /var/folders/d5/4tnwbfgn3n7gxb8c5xg88gdr0000gn/T/
XPC_SERVICE_NAME: application.org.blenderfoundation.blender.4888352.4888358
XPC_FLAGS: 0x0

DECALmachine: Installing PIL 8.3.1

Platform: Darwin
Python Binary: /Applications/Blender.app/Contents/Resources/3.0/python/bin/python3.9 True
Python Library: /Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9 True
Ensurepip: /Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9/ensurepip True

Modules: /Applications/Blender.app/Contents/Resources/3.0/scripts/modules True
Modules: /Users/giuseppe/Library/Application Support/Blender/3.0/scripts/modules False
Site-Packages: /Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9/site-packages True
User Site-Packages: /Users/giuseppe/.local/lib/python3.9/site-packages False
EasyInstall Path: /Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9/site-packages/easy_install.py False
EasyInstall User Path: /Users/giuseppe/.local/lib/python3.9/site-packages/easy_install.py False



Looking in links: /var/folders/d5/4tnwbfgn3n7gxb8c5xg88gdr0000gn/T/tmpylmt9pn6
Requirement already satisfied: setuptools in /Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9/site-packages (57.4.0)
Requirement already satisfied: pip in /Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9/site-packages (21.2.3)
ERROR: Could not install packages due to an OSError: [Errno 13] Permission denied: '/Users/giuseppe/.local/lib'
Check the permissions.
Traceback (most recent call last):
File "/Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9/runpy.py", line 197, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9/runpy.py", line 87, in _run_code
exec(code, run_globals)
File "/Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9/ensurepip/__main__.py", line 5, in <module>
sys.exit(ensurepip._main())
File "/Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9/ensurepip/__init__.py", line 210, in _main
return _bootstrap(
File "/Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9/ensurepip/__init__.py", line 129, in _bootstrap
return _run_pip(args + [p[0] for p in _PROJECTS], additional_paths)
File "/Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9/ensurepip/__init__.py", line 38, in _run_pip
return subprocess.run([sys.executable, "-c", code], check=True).returncode
File "/Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9/subprocess.py", line 528, in run
raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Applications/Blender.app/Contents/Resources/3.0/python/bin/python3.9', '-c', '\nimport runpy\nimport sys\nsys.path = [\'/var/folders/d5/4tnwbfgn3n7gxb8c5xg88gdr0000gn/T/tmpylmt9pn6/setuptools-57.4.0-py3-none-any.whl\', \'/var/folders/d5/4tnwbfgn3n7gxb8c5xg88gdr0000gn/T/tmpylmt9pn6/pip-21.2.3-py3-none-any.whl\'] + sys.path\nsys.argv[1:] = [\'install\', \'--no-cache-dir\', \'--no-index\', \'--find-links\', \'/var/folders/d5/4tnwbfgn3n7gxb8c5xg88gdr0000gn/T/tmpylmt9pn6\', \'--upgrade\', \'--user\', \'setuptools\', \'pip\']\nrunpy.run_module("pip", run_name="__main__", alter_sys=True)\n']' returned non-zero exit status 1.

ENVIRONMENT
USER: giuseppe
__CFBundleIdentifier: org.blenderfoundation.blender
COMMAND_MODE: unix2003
LOGNAME: giuseppe
PATH: /usr/bin:/bin:/usr/sbin:/sbin
SSH_AUTH_SOCK: /private/tmp/com.apple.launchd.vqwC3MgTW0/Listeners
SHELL: /bin/zsh
HOME: /Users/giuseppe
__CF_USER_TEXT_ENCODING: 0x1F5:0:15
TMPDIR: /var/folders/d5/4tnwbfgn3n7gxb8c5xg88gdr0000gn/T/
XPC_SERVICE_NAME: application.org.blenderfoundation.blender.6413244.6413250
XPC_FLAGS: 0x0

DECALmachine: Easy Installing PIL 8.3.1 (Admin)

Platform: Darwin
Python Binary: /Applications/Blender.app/Contents/Resources/3.0/python/bin/python3.9 True
Python Library: /Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9 True
Ensurepip: /Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9/ensurepip True

Modules: /Applications/Blender.app/Contents/Resources/3.0/scripts/modules True
Modules: /Users/giuseppe/Library/Application Support/Blender/3.0/scripts/modules False
Site-Packages: /Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9/site-packages True
User Site-Packages: /Users/giuseppe/.local/lib/python3.9/site-packages False
EasyInstall Path: /Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9/site-packages/easy_install.py False
EasyInstall User Path: /Users/giuseppe/.local/lib/python3.9/site-packages/easy_install.py False



Looking in links: /var/folders/d5/4tnwbfgn3n7gxb8c5xg88gdr0000gn/T/tmpzj5zbrdq
Requirement already satisfied: setuptools in /Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9/site-packages (57.4.0)
Requirement already satisfied: pip in /Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9/site-packages (21.2.3)
Requirement already satisfied: pip in /Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9/site-packages (21.2.3)
Collecting pip
Using cached pip-21.3.1-py3-none-any.whl (1.7 MB)
Installing collected packages: pip
Attempting uninstall: pip
Found existing installation: pip 21.2.3
Uninstalling pip-21.2.3:
Successfully uninstalled pip-21.2.3
Successfully installed pip-21.3.1

ENVIRONMENT
USER: giuseppe
__CFBundleIdentifier: org.blenderfoundation.blender
COMMAND_MODE: unix2003
LOGNAME: giuseppe
PATH: /usr/bin:/bin:/usr/sbin:/sbin
SSH_AUTH_SOCK: /private/tmp/com.apple.launchd.vqwC3MgTW0/Listeners
SHELL: /bin/zsh
HOME: /Users/giuseppe
__CF_USER_TEXT_ENCODING: 0x1F5:0:15
TMPDIR: /var/folders/d5/4tnwbfgn3n7gxb8c5xg88gdr0000gn/T/
XPC_SERVICE_NAME: application.org.blenderfoundation.blender.6413244.6413250
XPC_FLAGS: 0x0

DECALmachine: Installing PIL 8.3.1

Platform: Darwin
Python Binary: /Applications/Blender.app/Contents/Resources/3.0/python/bin/python3.9 True
Python Library: /Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9 True
Ensurepip: /Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9/ensurepip True

Modules: /Applications/Blender.app/Contents/Resources/3.0/scripts/modules True
Modules: /Users/giuseppe/Library/Application Support/Blender/3.0/scripts/modules False
Site-Packages: /Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9/site-packages True
User Site-Packages: /Users/giuseppe/.local/lib/python3.9/site-packages False
EasyInstall Path: /Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9/site-packages/easy_install.py False
EasyInstall User Path: /Users/giuseppe/.local/lib/python3.9/site-packages/easy_install.py False



Looking in links: /var/folders/d5/4tnwbfgn3n7gxb8c5xg88gdr0000gn/T/tmpn6sx0quv
Requirement already satisfied: setuptools in /Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9/site-packages (57.4.0)
Requirement already satisfied: pip in /Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9/site-packages (21.3.1)
ERROR: Could not install packages due to an OSError: [Errno 13] Permission denied: '/Users/giuseppe/.local/lib'
Check the permissions.
Traceback (most recent call last):
File "/Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9/runpy.py", line 197, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9/runpy.py", line 87, in _run_code
exec(code, run_globals)
File "/Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9/ensurepip/__main__.py", line 5, in <module>
sys.exit(ensurepip._main())
File "/Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9/ensurepip/__init__.py", line 210, in _main
return _bootstrap(
File "/Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9/ensurepip/__init__.py", line 129, in _bootstrap
return _run_pip(args + [p[0] for p in _PROJECTS], additional_paths)
File "/Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9/ensurepip/__init__.py", line 38, in _run_pip
return subprocess.run([sys.executable, "-c", code], check=True).returncode
File "/Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9/subprocess.py", line 528, in run
raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Applications/Blender.app/Contents/Resources/3.0/python/bin/python3.9', '-c', '\nimport runpy\nimport sys\nsys.path = [\'/var/folders/d5/4tnwbfgn3n7gxb8c5xg88gdr0000gn/T/tmpn6sx0quv/setuptools-57.4.0-py3-none-any.whl\', \'/var/folders/d5/4tnwbfgn3n7gxb8c5xg88gdr0000gn/T/tmpn6sx0quv/pip-21.2.3-py3-none-any.whl\'] + sys.path\nsys.argv[1:] = [\'install\', \'--no-cache-dir\', \'--no-index\', \'--find-links\', \'/var/folders/d5/4tnwbfgn3n7gxb8c5xg88gdr0000gn/T/tmpn6sx0quv\', \'--upgrade\', \'--user\', \'setuptools\', \'pip\']\nrunpy.run_module("pip", run_name="__main__", alter_sys=True)\n']' returned non-zero exit status 1.

ENVIRONMENT
USER: giuseppe
__CFBundleIdentifier: org.blenderfoundation.blender
COMMAND_MODE: unix2003
LOGNAME: giuseppe
PATH: /usr/bin:/bin:/usr/sbin:/sbin
SSH_AUTH_SOCK: /private/tmp/com.apple.launchd.vqwC3MgTW0/Listeners
SHELL: /bin/zsh
HOME: /Users/giuseppe
__CF_USER_TEXT_ENCODING: 0x1F5:0:15
TMPDIR: /var/folders/d5/4tnwbfgn3n7gxb8c5xg88gdr0000gn/T/
XPC_SERVICE_NAME: application.org.blenderfoundation.blender.6413244.6413250
XPC_FLAGS: 0x0

DECALmachine: Installing PIL 8.3.1

Platform: Darwin
Python Binary: /Applications/Blender.app/Contents/Resources/3.0/python/bin/python3.9 True
Python Library: /Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9 True
Ensurepip: /Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9/ensurepip True

Modules: /Applications/Blender.app/Contents/Resources/3.0/scripts/modules True
Modules: /Users/giuseppe/Library/Application Support/Blender/3.0/scripts/modules False
Site-Packages: /Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9/site-packages True
User Site-Packages: /Users/giuseppe/.local/lib/python3.9/site-packages False
EasyInstall Path: /Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9/site-packages/easy_install.py False
EasyInstall User Path: /Users/giuseppe/.local/lib/python3.9/site-packages/easy_install.py False



Looking in links: /var/folders/d5/4tnwbfgn3n7gxb8c5xg88gdr0000gn/T/tmp6mu8lffi
Requirement already satisfied: setuptools in /Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9/site-packages (57.4.0)
Requirement already satisfied: pip in /Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9/site-packages (21.3.1)
ERROR: Could not install packages due to an OSError: [Errno 13] Permission denied: '/Users/giuseppe/.local/lib'
Check the permissions.
Traceback (most recent call last):
File "/Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9/runpy.py", line 197, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9/runpy.py", line 87, in _run_code
exec(code, run_globals)
File "/Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9/ensurepip/__main__.py", line 5, in <module>
sys.exit(ensurepip._main())
File "/Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9/ensurepip/__init__.py", line 210, in _main
return _bootstrap(
File "/Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9/ensurepip/__init__.py", line 129, in _bootstrap
return _run_pip(args + [p[0] for p in _PROJECTS], additional_paths)
File "/Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9/ensurepip/__init__.py", line 38, in _run_pip
return subprocess.run([sys.executable, "-c", code], check=True).returncode
File "/Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9/subprocess.py", line 528, in run
raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Applications/Blender.app/Contents/Resources/3.0/python/bin/python3.9', '-c', '\nimport runpy\nimport sys\nsys.path = [\'/var/folders/d5/4tnwbfgn3n7gxb8c5xg88gdr0000gn/T/tmp6mu8lffi/setuptools-57.4.0-py3-none-any.whl\', \'/var/folders/d5/4tnwbfgn3n7gxb8c5xg88gdr0000gn/T/tmp6mu8lffi/pip-21.2.3-py3-none-any.whl\'] + sys.path\nsys.argv[1:] = [\'install\', \'--no-cache-dir\', \'--no-index\', \'--find-links\', \'/var/folders/d5/4tnwbfgn3n7gxb8c5xg88gdr0000gn/T/tmp6mu8lffi\', \'--upgrade\', \'--user\', \'setuptools\', \'pip\']\nrunpy.run_module("pip", run_name="__main__", alter_sys=True)\n']' returned non-zero exit status 1.

ENVIRONMENT
USER: giuseppe
__CFBundleIdentifier: org.blenderfoundation.blender
COMMAND_MODE: unix2003
LOGNAME: giuseppe
PATH: /usr/bin:/bin:/usr/sbin:/sbin
SSH_AUTH_SOCK: /private/tmp/com.apple.launchd.vqwC3MgTW0/Listeners
SHELL: /bin/zsh
HOME: /Users/giuseppe
__CF_USER_TEXT_ENCODING: 0x1F5:0:15
TMPDIR: /var/folders/d5/4tnwbfgn3n7gxb8c5xg88gdr0000gn/T/
XPC_SERVICE_NAME: application.org.blenderfoundation.blender.6413244.6413250
XPC_FLAGS: 0x0

DECALmachine: Installing PIL 8.3.1

Platform: Darwin
Python Binary: /Applications/Blender.app/Contents/Resources/3.0/python/bin/python3.9 True
Python Library: /Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9 True
Ensurepip: /Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9/ensurepip True

Modules: /Applications/Blender.app/Contents/Resources/3.0/scripts/modules True
Modules: /Users/giuseppe/Library/Application Support/Blender/3.0/scripts/modules False
Site-Packages: /Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9/site-packages True
User Site-Packages: /Users/giuseppe/.local/lib/python3.9/site-packages False
EasyInstall Path: /Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9/site-packages/easy_install.py False
EasyInstall User Path: /Users/giuseppe/.local/lib/python3.9/site-packages/easy_install.py False



Looking in links: /var/folders/d5/4tnwbfgn3n7gxb8c5xg88gdr0000gn/T/tmpch_i2m_z
Requirement already satisfied: setuptools in /Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9/site-packages (57.4.0)
Requirement already satisfied: pip in /Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9/site-packages (21.3.1)
ERROR: Could not install packages due to an OSError: [Errno 13] Permission denied: '/Users/giuseppe/.local/lib'
Check the permissions.
Traceback (most recent call last):
File "/Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9/runpy.py", line 197, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9/runpy.py", line 87, in _run_code
exec(code, run_globals)
File "/Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9/ensurepip/__main__.py", line 5, in <module>
sys.exit(ensurepip._main())
File "/Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9/ensurepip/__init__.py", line 210, in _main
return _bootstrap(
File "/Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9/ensurepip/__init__.py", line 129, in _bootstrap
return _run_pip(args + [p[0] for p in _PROJECTS], additional_paths)
File "/Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9/ensurepip/__init__.py", line 38, in _run_pip
return subprocess.run([sys.executable, "-c", code], check=True).returncode
File "/Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9/subprocess.py", line 528, in run
raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Applications/Blender.app/Contents/Resources/3.0/python/bin/python3.9', '-c', '\nimport runpy\nimport sys\nsys.path = [\'/var/folders/d5/4tnwbfgn3n7gxb8c5xg88gdr0000gn/T/tmpch_i2m_z/setuptools-57.4.0-py3-none-any.whl\', \'/var/folders/d5/4tnwbfgn3n7gxb8c5xg88gdr0000gn/T/tmpch_i2m_z/pip-21.2.3-py3-none-any.whl\'] + sys.path\nsys.argv[1:] = [\'install\', \'--no-cache-dir\', \'--no-index\', \'--find-links\', \'/var/folders/d5/4tnwbfgn3n7gxb8c5xg88gdr0000gn/T/tmpch_i2m_z\', \'--upgrade\', \'--user\', \'setuptools\', \'pip\']\nrunpy.run_module("pip", run_name="__main__", alter_sys=True)\n']' returned non-zero exit status 1.

ENVIRONMENT
USER: giuseppe
__CFBundleIdentifier: org.blenderfoundation.blender
COMMAND_MODE: unix2003
LOGNAME: giuseppe
PATH: /usr/bin:/bin:/usr/sbin:/sbin
SSH_AUTH_SOCK: /private/tmp/com.apple.launchd.vqwC3MgTW0/Listeners
SHELL: /bin/zsh
HOME: /Users/giuseppe
__CF_USER_TEXT_ENCODING: 0x1F5:0:15
TMPDIR: /var/folders/d5/4tnwbfgn3n7gxb8c5xg88gdr0000gn/T/
XPC_SERVICE_NAME: application.org.blenderfoundation.blender.6413244.6413250
XPC_FLAGS: 0x0

DECALmachine: Installing PIL 8.3.1

Platform: Darwin
Python Binary: /Applications/Blender.app/Contents/Resources/3.0/python/bin/python3.9 True
Python Library: /Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9 True
Ensurepip: /Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9/ensurepip True

Modules: /Applications/Blender.app/Contents/Resources/3.0/scripts/modules True
Modules: /Users/giuseppe/Library/Application Support/Blender/3.0/scripts/modules False
Site-Packages: /Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9/site-packages True
User Site-Packages: /Users/giuseppe/.local/lib/python3.9/site-packages False
EasyInstall Path: /Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9/site-packages/easy_install.py False
EasyInstall User Path: /Users/giuseppe/.local/lib/python3.9/site-packages/easy_install.py False



Looking in links: /var/folders/d5/4tnwbfgn3n7gxb8c5xg88gdr0000gn/T/tmpv2z7ljez
Requirement already satisfied: setuptools in /Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9/site-packages (57.4.0)
Requirement already satisfied: pip in /Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9/site-packages (21.3.1)
ERROR: Could not install packages due to an OSError: [Errno 13] Permission denied: '/Users/giuseppe/.local/lib'
Check the permissions.
Traceback (most recent call last):
File "/Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9/runpy.py", line 197, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9/runpy.py", line 87, in _run_code
exec(code, run_globals)
File "/Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9/ensurepip/__main__.py", line 5, in <module>
sys.exit(ensurepip._main())
File "/Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9/ensurepip/__init__.py", line 210, in _main
return _bootstrap(
File "/Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9/ensurepip/__init__.py", line 129, in _bootstrap
return _run_pip(args + [p[0] for p in _PROJECTS], additional_paths)
File "/Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9/ensurepip/__init__.py", line 38, in _run_pip
return subprocess.run([sys.executable, "-c", code], check=True).returncode
File "/Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9/subprocess.py", line 528, in run
raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Applications/Blender.app/Contents/Resources/3.0/python/bin/python3.9', '-c', '\nimport runpy\nimport sys\nsys.path = [\'/var/folders/d5/4tnwbfgn3n7gxb8c5xg88gdr0000gn/T/tmpv2z7ljez/setuptools-57.4.0-py3-none-any.whl\', \'/var/folders/d5/4tnwbfgn3n7gxb8c5xg88gdr0000gn/T/tmpv2z7ljez/pip-21.2.3-py3-none-any.whl\'] + sys.path\nsys.argv[1:] = [\'install\', \'--no-cache-dir\', \'--no-index\', \'--find-links\', \'/var/folders/d5/4tnwbfgn3n7gxb8c5xg88gdr0000gn/T/tmpv2z7ljez\', \'--upgrade\', \'--user\', \'setuptools\', \'pip\']\nrunpy.run_module("pip", run_name="__main__", alter_sys=True)\n']' returned non-zero exit status 1.

ENVIRONMENT
USER: giuseppe
__CFBundleIdentifier: org.blenderfoundation.blender
COMMAND_MODE: unix2003
LOGNAME: giuseppe
PATH: /usr/bin:/bin:/usr/sbin:/sbin
SSH_AUTH_SOCK: /private/tmp/com.apple.launchd.vqwC3MgTW0/Listeners
SHELL: /bin/zsh
HOME: /Users/giuseppe
__CF_USER_TEXT_ENCODING: 0x1F5:0:15
TMPDIR: /var/folders/d5/4tnwbfgn3n7gxb8c5xg88gdr0000gn/T/
XPC_SERVICE_NAME: application.org.blenderfoundation.blender.6413244.6413250
XPC_FLAGS: 0x0

DECALmachine: Installing PIL 8.3.1 (Admin)

Platform: Darwin
Python Binary: /Applications/Blender.app/Contents/Resources/3.0/python/bin/python3.9 True
Python Library: /Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9 True
Ensurepip: /Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9/ensurepip True

Modules: /Applications/Blender.app/Contents/Resources/3.0/scripts/modules True
Modules: /Users/giuseppe/Library/Application Support/Blender/3.0/scripts/modules False
Site-Packages: /Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9/site-packages True
User Site-Packages: /Users/giuseppe/.local/lib/python3.9/site-packages False
EasyInstall Path: /Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9/site-packages/easy_install.py False
EasyInstall User Path: /Users/giuseppe/.local/lib/python3.9/site-packages/easy_install.py False



Looking in links: /var/folders/d5/4tnwbfgn3n7gxb8c5xg88gdr0000gn/T/tmpoi06txe5
Requirement already satisfied: setuptools in /Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9/site-packages (57.4.0)
Requirement already satisfied: pip in /Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9/site-packages (21.3.1)
Requirement already satisfied: pip in /Applications/Blender.app/Contents/Resources/3.0/python/lib/python3.9/site-packages (21.3.1)
Collecting Pillow==8.3.1
Using cached Pillow-8.3.1-cp39-cp39-macosx_11_0_arm64.whl (2.7 MB)
Installing collected packages: Pillow
Successfully installed Pillow-8.3.1
Successfully imported PIL's Image module. PIL is ready to go.

ENVIRONMENT
USER: giuseppe
__CFBundleIdentifier: org.blenderfoundation.blender
COMMAND_MODE: unix2003
LOGNAME: giuseppe
PATH: /usr/bin:/bin:/usr/sbin:/sbin
SSH_AUTH_SOCK: /private/tmp/com.apple.launchd.vqwC3MgTW0/Listeners
SHELL: /bin/zsh
HOME: /Users/giuseppe
__CF_USER_TEXT_ENCODING: 0x1F5:0:15
TMPDIR: /var/folders/d5/4tnwbfgn3n7gxb8c5xg88gdr0000gn/T/
XPC_SERVICE_NAME: application.org.blenderfoundation.blender.6413244.6413250
XPC_FLAGS: 0x0
